### ISSUE TITLE
Tutorial step 11 - Key Error 

### ISSUE THREAD

**Issue by swelbo** [ctmrbio/optivag#2]
At this step i'm getting a bunch of Key Errors. This is despite the genome file being in my downloaded genomes folder. Any idea as to why this might be happening? Only solution i have managed to find is to remove the file. 

`python database/tools/map_seq_tax.py -t all_taxa.tsv -g downloaded_genomes/`

```
Traceback (most recent call last):
  File "database/tools/map_seq_tax.py", line 65, in <module>
    main(args.taxa, args.genomes, args.out)
  File "database/tools/map_seq_tax.py", line 40, in main
    make_list(id_dict, genomes, outfile)
  File "database/tools/map_seq_tax.py", line 29, in make_list
    tax_id = id_dict[genome]
KeyError: 'GCF_001691605.1_ASM169160v1_genomic.fna'
```

**Comment by luhugerth** [comment]
Not sure...

Did everything work correctly in the previous steps? Did you have to do a lot of updates to the refseq_taxa.tsv and genbank_taxa.tsv for the downloads to work? I'm wondering if there could possibly be a discrepancy between the files downloaded and the ID:s that made it to the "all_taxa.tsv" file.

Sorry I'm not being super helpful. Can you try to explain with as much detail as possible what you've done so far?

**Comment by swelbo** [comment]
Hello! Thanks for the reply.

So.. 

I first ran:

`python database/tools/extract_vaginal_taxa.py --assem assembly_summary_refseq.txt --to-use database/db/genome_info/v0.3/bacteria_list.tsv --found outdir/refseq_genomes_found.tsv 
--not-found outdir/refseq_missing_genomes.tsv`

I then edited a copy of bacteria_list.tsv in a new folder called v0.4 based on changes i determined using the refseq_missing_genomes.tsv. I didn't do this extensively but planned to revisit once i got the whole thing up and running. Any changes that i made i noted down in a new file named new_v0.4.txt to the same-ish format as previous edits. 

I then ran:

`python ../database/tools/filter_found_genomes.py -i refseq_genomes_found.tsv -g get_refseq_genomes.sh -p get_refseq_proteins.sh -t refseq_taxa.tsv`

I ran the two scripts and bumped into a few errors as per your guide. I edited these until all genomes downloaded successfully. 

Next i re-ran everything in refseq_missing_genomes.tsv against the assembly_summary_genbank.txt file and followed the same steps as before. 

I combined the final two files using:

`cat refseq_taxa.tsv genbank_taxa.tsv > all_taxa.tsv`

and ... ran:

`python map_seq_tax.py -t all_taxa.tsv -g /home/sally/Archive/Archive2/databases/optivag/outdir/nucleotide`

This is where i met the KeyErrors. I removed bad entries until it worked. I then went through the Kraken/Bracken custome DB workflow which was all fine. 

I guess one other thing to note is i split the downloads between two folder nucleotide and protein. I wasn't sure how Kraken handles different file types. Perhaps you have a better understanding of this? 

Thanks again! 
Tom 

edit: I should say the database worked really nicely against our standard control so thanks for your energy !

**Comment by luhugerth** [comment]
Thanks for the detailed explanation! Unfortunately, I'm still not sure XD

Somehow there are downloaded `.fna` files in your folder that were not in either your final `refseq_taxa.tsv`nor in  `genbank_taxa.tsv`. I have a vague recollection of this happening when genomes get version bumped e.g. from v1 to v2, but this doesn't seem to be the case for you...

Please let me know if you figure it out - and also looking forward to seeing your v0.4 species compilation! Please make a pull request when you're comfortable sharing it.

**Comment by swelbo** [comment]
Will do, thanks!
